- name: Create isucon user with full privileges
  become: true
  ansible.builtin.shell: |
    mysql --execute="
      CREATE USER IF NOT EXISTS 'isucon'@'{{ item }}' IDENTIFIED BY 'isucon';
      GRANT ALL PRIVILEGES ON *.* TO 'isucon'@'{{ item }}' WITH GRANT OPTION;
    "
  args:
    executable: /bin/bash
  with_items:
    - 'localhost'
    - "{{ internal_ips.S1 }}"
    - "{{ internal_ips.S2 }}"
    - "{{ internal_ips.S3 }}"

- name: Deploy file
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: restart_db
  with_items:
    - etc/mysql/mysql.conf.d/mysqld.cnf
