- name: Deploy config
  become: true
  ansible.builtin.template:
    src: "../webapp/nginx/{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart_nginx
  with_items:
    - etc/nginx/sites-enabled/isupipe.conf
