- name: Add webapp IP and hostname to /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ webapp_ip }} pipe.u.isucon.local"
    regexp: "^{{ webapp_ip }}\\s+pipe.u.isucon.local"
  vars:
    webapp_ip: "{{ internal_ips.S1 }}"
