all:
  vars:
    hosts_ips:
      S1: isucon-server1
      S2: isucon-server2
      S3: isucon-server3
      B: isucon-server4
    internal_ips:
      S1: 172.31.43.188
      S2: 172.31.46.244
      S3: 172.31.33.83
      B: 172.31.44.63
    nginx_ip: "{{ internal_ips.S1 }}"
    pdns_ip: "{{ internal_ips.S3 }}"
    db_ip: "{{ internal_ips.S2 }}"
    main_web_ip: "{{ internal_ips.S3 }}"
    sub_web_ip: "{{ internal_ips.S1 }}"
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/wsl.pem
  children:
    target:
      children:
        nginx:
          hosts:
            nginx01:
              ansible_host: "{{ hosts_ips.S1 }}"
        webapp:
          hosts:
            webapp01:
              ansible_host: "{{ hosts_ips.S1 }}"
            webapp02:
              ansible_host: "{{ hosts_ips.S2 }}"
            webapp03:
              ansible_host: "{{ hosts_ips.S3 }}"
        db:
          hosts:
            db:
              ansible_host: "{{ hosts_ips.S2 }}"
        pdns:
          hosts:
            pdns01:
              ansible_host: "{{ hosts_ips.S3 }}"
    outsider:
      hosts:
        benchmarker:
          ansible_host: "{{ hosts_ips.B }}"
