---
- name: Replace ISUCON13_POWERDNS_SUBDOMAIN_ADDRESS with hosts_ips.S1
  ansible.builtin.lineinfile:
    path: "/home/isucon/env.sh"
    regexp: '^ISUCON13_POWERDNS_SUBDOMAIN_ADDRESS='
    line: "ISUCON13_POWERDNS_SUBDOMAIN_ADDRESS={{ internal_ips.S1  }}"
    backup: true  # 変更前にバックアップを作成します
  notify: restart_webapp  # 必要に応じてサービス再起動等のアクションを追加
